### ISSUE TITLE
Добавить в модели функции трансформации под firestore

### ISSUE THREAD

**Issue by 1ce-scream** [1ce-scream/GB_PartyScheduler#107]

**Comment by kozhemin** [comment]
По гайду
https://firebase.google.com/docs/firestore/manage-data/add-data#custom_objects

**Comment by 1ce-scream** [comment]
Для получения данных
https://firebase.google.com/docs/firestore/query-data/get-data?authuser=0#custom_objects

Для слушателей
https://stackoverflow.com/questions/61571857/swift-firestore-custom-objects-from-query-while-listening-for-realtime-updates-w

**Comment by 1ce-scream** [comment]
[pull](https://github.com/1ce-scream/GB_PartyScheduler/pull/155)
