### ISSUE TITLE
Доработать ссылки между документами - Reference

### ISSUE THREAD

**Issue by kozhemin** [1ce-scream/GB_PartyScheduler#121]
Пример:
https://stackoverflow.com/questions/50012956/firestore-how-to-store-reference-to-document-how-to-retrieve-it

Далее зарефакторить механизм удаления события. 
- Выпилить отдельное удаление Todo/Users/Polls и тд.

**Comment by kozhemin** [comment]
https://github.com/firebase/extensions/issues/841

**Comment by kozhemin** [comment]
Тут на js, но в целом все понятно:
https://stackoverflow.com/questions/46568850/what-is-firebase-firestore-reference-data-type-good-for

**Comment by kozhemin** [comment]
https://github.com/1ce-scream/GB_PartyScheduler/pull/154

**Comment by 1ce-scream** [comment]
Перестали работать вкладки для участников события. Не отображаются участники (и при выборе своего статуса это не отмечается у организатора), также не отображаются затраты и голосования. На странице события участник не видит количество участников (всегда 0)

**Comment by kozhemin** [comment]
В  базе поменялись ряд связей между данными, так как база не продуктовая миграцию не делал, но и зачистить забыл. Сейчас все старое удалил. Попробуй прогнать работу приложения
