### ISSUE TITLE
Добавить кэширование аватаров

### ISSUE THREAD

**Issue by kozhemin** [1ce-scream/GB_PartyScheduler#142]
Сейчас при каждом показе/обновлении изображения аватаров запрашиваются по сети

**Comment by 1ce-scream** [comment]
Есть уже готовая штука (доработанный asyncImage)  https://github.com/lorenzofiamingo/swiftui-cached-async-image
Или сами писать будем?

**Comment by kozhemin** [comment]
О, давай попробуем подключить!

**Comment by 1ce-scream** [comment]
https://github.com/1ce-scream/GB_PartyScheduler/pull/168
