### ISSUE TITLE
Исправить картинку на лонч скрине

### ISSUE THREAD

**Issue by 1ce-scream** [1ce-scream/GB_PartyScheduler#153]
На реальном девайсе её почему-то размазывает. 
![IMG_4464](https://user-images.githubusercontent.com/86912772/187681118-648aeafe-4e70-49b7-bc16-e37342008157.jpg)

**Comment by 1ce-scream** [comment]
По ходу дела, уже не надо. С Xcode 14 ошибка ушла.

**Comment by kozhemin** [comment]
Все таки ошибка осталась..

**Comment by 1ce-scream** [comment]
https://github.com/1ce-scream/GB_PartyScheduler/pull/188
