### ISSUE TITLE
Push уведомления на приглашение в событие

### ISSUE THREAD

**Issue by 1ce-scream** [1ce-scream/GB_PartyScheduler#160]
После добавления участника в событие и если он есть в базе, то отправлять уведомление. Или может быть просто на изменение списка событий. Тут надо подумать.

**Comment by kozhemin** [comment]
+ да, я уже тоже думал. Надо отправлять  push уведомление при добавлении нового участника.... если конечно он есть в базе, а вот если его нет то уже делать или sms или email или еще какое уведомление со ссылкой на установку приложения

**Comment by kozhemin** [comment]
https://github.com/1ce-scream/GB_PartyScheduler/pull/170

**Comment by 1ce-scream** [comment]
И я об этом думал. Но просто отправлять смс или email с сервиса не получится. Могут притянуть за обработку персональных данных без согласия. А вот поработать над функционалом отправки смс через iMessage или письма через почту, чтоб пользователь был инициатором и отправителем можно. Но это уже другая история :)
