### ISSUE TITLE
На главной странице события на к-во участников сделать ссылку на таб с пользователями

### ISSUE THREAD

**Issue by kozhemin** [1ce-scream/GB_PartyScheduler#179]
люди которые впервые видят пытаются туда жать и не могут понять как посмотреть пользователей события

**Comment by 1ce-scream** [comment]
Я вот тоже об этом думал.
https://github.com/1ce-scream/GB_PartyScheduler/issues/165

**Comment by kozhemin** [comment]
https://github.com/1ce-scream/GB_PartyScheduler/pull/186
