### ISSUE TITLE
Добавить сортировку событий, новые сверху, прошедшие архивировать

### ISSUE THREAD

**Issue by kozhemin** [1ce-scream/GB_PartyScheduler#180]

**Comment by 1ce-scream** [comment]
Архивация прошедших событий отличная идея. Сортировку точно надо сделать по дате. И можно связать с этими шью https://github.com/1ce-scream/GB_PartyScheduler/issues/162

**Comment by kozhemin** [comment]
https://github.com/1ce-scream/GB_PartyScheduler/pull/190
