### ISSUE TITLE
На странице профиля баг при сохранении данных

### ISSUE THREAD

**Issue by kozhemin** [1ce-scream/GB_PartyScheduler#183]
Не сохраняется Имя, Фамилия, Email 
жмем сохранить и поля просто очищаются

**Comment by 1ce-scream** [comment]
Кстати, по ходу дела этот баг связан с багом https://github.com/1ce-scream/GB_PartyScheduler/issues/178 
Какой-то косяк в логике проверки на наличие пользователя в бд всплыл.

**Comment by 1ce-scream** [comment]
Все проверил, на iOS 15.5 и 16.0, баг воспроизвести не удалось. (пользователя для тестов удалял непосредственно из бд)
