### ISSUE TITLE
Не слать push уведомление себе

### ISSUE THREAD

**Issue by kozhemin** [1ce-scream/GB_PartyScheduler#184]
Когда сам редактируешь событие, то сам же и получаю push
+ необходимо отслеживать что данные реально изменились. Сейчас push происходит безусловно

**Comment by kozhemin** [comment]
Поправил push уведомления

**Comment by 1ce-scream** [comment]
А где пул?)

**Comment by kozhemin** [comment]
Там в отдельном микросервисе push отправляется https://github.com/kozhemin/PartySchedulerNotification
Кстати добавил к тебя к проекту тоже. Правда он на Golang написан
