### ISSUE TITLE
Добавить отображение ошибок/уведомлений

### ISSUE THREAD

**Issue by kozhemin** [1ce-scream/GB_PartyScheduler#19]
Пример:
https://trailingclosure.com/notification-banner-using-swiftui/
https://github.com/jboullianne/SwiftUIBanner

![изображение](https://user-images.githubusercontent.com/7480673/181190878-9c784197-1b1c-4eaf-bf59-24c7de251f81.png)

**Comment by kozhemin** [comment]
https://github.com/1ce-scream/GB_PartyScheduler/pull/60

**Comment by 1ce-scream** [comment]
Отлично
