### ISSUE TITLE
Баг со списком участников

### ISSUE THREAD

**Issue by 1ce-scream** [1ce-scream/GB_PartyScheduler#204]
Если приглашенный участник добавит другого пользователя в событие, то оно почему-то пропадает из списка событий у организатора (организатор больше не видит этого события в списке, но у всех остальных участников оно есть в списке)

Плюс, если организатор приглашает кого-то, то всех участников выкидывает с этой вкладки на первую вкладку таббара.

**Comment by kozhemin** [comment]
Баг со списокм участников поправил. 
по поводу навигации нашел интересную и простую библиотеку https://github.com/vuvdv3101/VNavigator как pod не стал подключать к проекту, просто позаимствовал код

**Comment by kozhemin** [comment]
https://github.com/1ce-scream/GB_PartyScheduler/pull/218

**Comment by 1ce-scream** [comment]
Отличная работа! И пару моментов надо подправить. У приглашенного пользователя событие в списке появляется без признака нового события(признак появляется после перезахода в приложение). И alertmanager начал спавниться при каждом заходе на таббар (его надо передать как environmentObject на таббар, ввиду новой навигации) У приглашенного пользователя почему-то создается несколько eventViewModel. Одна лишняя при переходе на любой таб. А когда появляется еще одна не понятно, но больше 3-х штук не было, странные дела.

<img width="351" alt="Снимок экрана 2022-11-01 в 14 44 11" src="https://user-images.githubusercontent.com/86912772/199225492-50f26e3a-c1a6-4481-9468-6b194490e6e6.png">

**Comment by kozhemin** [comment]
Ок! гляну. А как вот это отобразить ?


![Image](https://user-images.githubusercontent.com/7480673/199588114-8700b296-05de-4cd0-808e-232d36f08aa5.png)

**Comment by 1ce-scream** [comment]
Это отображение появляется когда запускаешь дебаггер памяти. 

![Image](https://user-images.githubusercontent.com/86912772/199661347-7c37c25e-2e7a-4e61-a7a1-f43843f7407d.png)

**Comment by kozhemin** [comment]
Пофиксил главный экран событий. Поправил подключение к AlertManager

После запуска приложения открыл событие и прошелся по всем тамбам 3 раза. Запустил debug memory получил картинку:


![Image](https://user-images.githubusercontent.com/7480673/199759546-a5a508b6-b6ce-4ef1-a88c-306abfb55792.png)
