### ISSUE TITLE
При создании события слишком много обязательных полей

### ISSUE THREAD

**Issue by kozhemin** [1ce-scream/GB_PartyScheduler#211]
Предлагаю оставить обязательными только название и даты

**Comment by 1ce-scream** [comment]
Тут надо оставить обязательным только название и может быть одно из описаний. С датами надо подумать и однозначно будут проблемы, они изначально имеют значение текущего времени при инициализации вью модели. А место рано или поздно будет добавляться через интерфейс карт.

**Comment by kozhemin** [comment]
https://github.com/1ce-scream/GB_PartyScheduler/pull/237
