### ISSUE TITLE
Доработки страницы профиля

### ISSUE THREAD

**Issue by kozhemin** [1ce-scream/GB_PartyScheduler#212]
- В полях ввода отображать ранее введенные данные
- Добавить валидацию email адреса
- Выход сделать с подтверждением

**Comment by 1ce-scream** [comment]
Только первый пункт вызовет проблемы, изначально так и было, но пришлось изменить(не помню почему) Остальные пункты поддерживаю.

**Comment by 1ce-scream** [comment]
https://github.com/1ce-scream/GB_PartyScheduler/pull/247
