### ISSUE TITLE
При редактировании события не загружается фото

### ISSUE THREAD

**Issue by kozhemin** [1ce-scream/GB_PartyScheduler#213]
При сохранении или отмене появляется alert - с просьбой подождать, но ничего при этом не происходит.

Как минимум при отмене надо давать выйти и прервать операцию

**Comment by kozhemin** [comment]
Попытался удалить фото чтобы выйти из режима редактирования, но фото не удаляется. По факту приложение зависло на одном экране

**Comment by kozhemin** [comment]
Перезапустил приложение и попытался загрузить. Теперь сработало

**Comment by 1ce-scream** [comment]
Логику работы с фото надо переработать. Я тоже уже встретил пару проблем при редактировании события. По идее выходом будем получение списка фото по id события, вместо хранения ссылок на эти фото в самой модели события. 
https://firebase.google.com/docs/storage/ios/list-files
