### ISSUE TITLE
Переработать секцию организатора события

### ISSUE THREAD

**Issue by 1ce-scream** [1ce-scream/GB_PartyScheduler#230]
Если пользователя нет в БД (он не заполнял имя/фамилию и тд), то секция висит как пустой roundedRectangle и это надо исправить. Либо отображать заглушку, либо скрывать её.

**Comment by kozhemin** [comment]
Поправил отображение. Точнее скрыл если в базе owner пустой

https://github.com/1ce-scream/GB_PartyScheduler/pull/242
