### ISSUE TITLE
Продумать механизм оповещения пользователей

### ISSUE THREAD

**Issue by kozhemin** [1ce-scream/GB_PartyScheduler#231]
Надо что-то придумать для оповещения пользователя у которого еще нет приложения, но которого добавили к событию

**Comment by 1ce-scream** [comment]
Я ничего лучше, чем использовать ShareSheet пока не придумал пока. Просто дать организатору возможность отправлять ссылку на приложуху удобным ему способом.

**Comment by kozhemin** [comment]
Хорошая идея!

**Comment by kozhemin** [comment]
https://github.com/1ce-scream/GB_PartyScheduler/pull/257
