### ISSUE TITLE
Баг приглашения пользователей в событие

### ISSUE THREAD

**Issue by 1ce-scream** [1ce-scream/GB_PartyScheduler#235]
Если организатора нет в бд (он не заполнял имя/фамилию и тд), то после приглашения пользователя у организатора событие исчезает из списка. Тут надо либо запретить создавать события пока не заполнен профиль, либо изменить логику добавления других пользователей. Либо создавать профиль-заглушку при регистрации (это поможет избавиться от нескольких проблем)

**Comment by kozhemin** [comment]
Поправил функцинал добавления/удаления пользователя к событию
https://github.com/1ce-scream/GB_PartyScheduler/pull/239
