### ISSUE TITLE
Если всем разрешили добавлять новых участников - то разрешить и удалять их тоже

### ISSUE THREAD

**Issue by kozhemin** [1ce-scream/GB_PartyScheduler#241]
Сейчас добавить можно, а удалить уже нет...

@1ce-scream что скажешь?

**Comment by 1ce-scream** [comment]
А вот тут не знаю. Мне кажется, что если разрешить всем подряд удалять участников, то может начаться хаос. С приглашениями в этом плане проще. Организаторам относительно крупных мероприятий на руку много приглашений, а для мелких событий организатор может не включать эту функцию.

**Comment by kozhemin** [comment]
Согласен. Отбой
