### ISSUE TITLE
Не слать push уведомление если нет изменений

### ISSUE THREAD

**Issue by kozhemin** [1ce-scream/GB_PartyScheduler#256]
при редактировании фото/текста взводить специальный флаг... сейчас push происходит безусловно при сохранении

**Comment by 1ce-scream** [comment]
При редактировании фото есть функция вычисляющая наличие в них изменения и тут флаг подойдет.  А для текста лучше хэш считать или что-то в этом роде, можно же просто убрать одну букву и снова ее добавить и флаг сработает хотя изменений нет.

**Comment by kozhemin** [comment]
Если ты про метод checkIsPhotoChanged то он не возвращает ответа, и внутри себя делает сохранение. А на переменную isShownUploadingProgress тоже не завязаться... 

> А для текста лучше хэш считать 

Да, написал для этого простую реализацию...
https://github.com/1ce-scream/GB_PartyScheduler/compare/develop...feature/issue-256?expand=1

**Comment by 1ce-scream** [comment]
> Если ты про метод checkIsPhotoChanged то он не возвращает ответа, и внутри себя делает сохранение. А на переменную isShownUploadingProgress тоже не завязаться...

Я имел ввиду, что можно использовать эту функцию и добавить для нее флаг наличия изменений. Внутри функции везде, где есть setTimerSpeed() можно взводить этот флаг.

**Comment by kozhemin** [comment]
Готово, https://github.com/1ce-scream/GB_PartyScheduler/pull/268
