### ISSUE TITLE
Доработать переходы между экранами

### ISSUE THREAD

**Issue by 1ce-scream** [1ce-scream/GB_PartyScheduler#30]
Просто раскидать экраны по табБарам и добавить недостающие переходы

**Comment by kozhemin** [comment]
ссылки по теме решения проблем с переходом из ТабБара:

https://solveforum.com/forums/threads/solved-swiftui-hidesbottombarwhenpushed-equivalent.1323621/

https://github.com/siteline/SwiftUI-Introspect

https://medium.com/@wasimshigri/hide-tabbar-in-swiftui-8a27e617cc17

https://github.com/r-plus/swiftui-hide-tab-when-push/blob/main/swiftui-hide-tab-when-push.playground/Contents.swift

**Comment by kozhemin** [comment]
https://github.com/r-plus/swiftui-hide-tab-when-push
