### ISSUE TITLE
Refactoring - зависимостей

### ISSUE THREAD

**Issue by kozhemin** [1ce-scream/GB_PartyScheduler#38]
Проверить можно ли как-то уменьшить список зависимостей.
Есть мнение что подтянулось слишком много лишнего

> они там кучей сами подтянулись после того как подключили FireBase Auth

**Comment by 1ce-scream** [comment]
Как ты смотришь на то, что бы перейти на поды?

**Comment by kozhemin** [comment]
> Как ты смотришь на то, что бы перейти на поды?

Не вижу проблем. Думаешь там меньше будет зависимостей? В PM меня напрягает одно - при каждом запуске Xcode он начинает их заново загружать.... как минимум оооочень странное поведение

**Comment by 1ce-scream** [comment]
Да, что-то мне подсказывает, что и зависимостей станет меньше и заново загружаться не будет. Да и проблем должен стать меньше, мне периодически приходится удалять зависимости и заново их добавлять тк PM почему-то косячит.

**Comment by 1ce-scream** [comment]
https://github.com/1ce-scream/GB_PartyScheduler/pull/166

**Comment by 1ce-scream** [comment]
По ходу дела, все стало еще хуже в плане зависимостей. И еще куча деприкейтид штук повсплывала. 

![Image](https://user-images.githubusercontent.com/86912772/190391781-1ec76c8e-d1a1-4011-b9b4-345cc3d4ab59.png)



![Image](https://user-images.githubusercontent.com/86912772/190391811-9e57a6fd-5949-464a-9deb-1b16614a608c.png)

**Comment by kozhemin** [comment]
ааа, там видимо надо указывать конертные библиотеки, а не целиком firebase

**Comment by 1ce-scream** [comment]
Ну да, там указано 6 конкретных библиотек, а в итоге с зависимостями выходит 25 подов. Что думаешь, оставим SPM или поды будем использовать?

**Comment by kozhemin** [comment]
> Что думаешь, оставим SPM или поды будем использовать?

Давай на поды перейдем.
