### ISSUE TITLE
Экран приглашения/добавления гостя в событие

### ISSUE THREAD

**Issue by 1ce-scream** [1ce-scream/GB_PartyScheduler#46]
Экран содержит список контактов и поиск по номеру телефона в базе
При отсутствии пользователя в базе, всплывает alert или секция предлагающие перейти на sheet и отправить приглашение по e-mail/телефону на событие и в приложение :)

**Comment by kozhemin** [comment]
https://github.com/1ce-scream/GB_PartyScheduler/pull/52
