### ISSUE TITLE
Выбрать иконку для приложения

### ISSUE THREAD

**Issue by kozhemin** [1ce-scream/GB_PartyScheduler#50]
Необходимо для публикации в TestFlight 

Важно. Должна быть иконка размера 1024x1024 остальные можно конвертировать из нее

**Comment by kozhemin** [comment]
@1ce-scream предлагаю накидать идей на иконку приложения. и можно будет попробовать опубликовать его как промежуточный релиз.

- https://gorodprima.ru/wp-content/uploads/2018/12/illust-35-768x768.jpg
- https://gorodprima.ru/wp-content/uploads/2018/12/smotret-kino.jpg
- https://gorodprima.ru/wp-content/uploads/2018/12/menu_mega-25.jpg

**Comment by 1ce-scream** [comment]
https://www.pngegg.com/ru/png-zkbza
https://www.pngegg.com/ru/png-xvsts
https://www.pngegg.com/ru/png-bfeon
https://www.pngegg.com/ru/png-bxvuc
https://www.pngegg.com/ru/png-dhyjz
https://www.pngegg.com/ru/png-zmzzb

**Comment by kozhemin** [comment]
Пока остановились предварительно на этих:
- https://www.pngegg.com/ru/png-bxvuc 
- https://www.pngegg.com/ru/png-zkbza

А далее будем смотреть по факту как на темном фоне будет смотреться
