### ISSUE TITLE
Revision EventView Добавить кнопки или переключатель приду / не приду / сомневаюсь

### ISSUE THREAD

**Issue by 1ce-scream** [1ce-scream/GB_PartyScheduler#54]
Скорее всего это стоит добавить на экран детальной инфы о событии. Естественно, с проверкой не является ли пользователем создателем/организатором события. В идеале, на этом экране нижний блок info перенести наверх, а вместо него добавить переключатель

Это наверх 
<img width="344" alt="Снимок экрана 2022-08-06 в 14 26 53" src="https://user-images.githubusercontent.com/86912772/183246961-7017b50b-bd9b-4a16-9376-946056b4de25.png">

вместо этого (или можно просто коротенькое описание оставить, как в ячейке)
<img width="344" alt="Снимок экрана 2022-08-06 в 14 27 16" src="https://user-images.githubusercontent.com/86912772/183246990-a4731430-c5d2-49c7-8b8a-5d87c71e46b7.png">

**Comment by kozhemin** [comment]
https://github.com/1ce-scream/GB_PartyScheduler/pull/111
