### ISSUE TITLE
Восстановление пароля (прототип)

### ISSUE THREAD

**Issue by 1ce-scream** [1ce-scream/GB_PartyScheduler#8]
Пользователь выбирает вариант куда отправить код, вводит код и вводит новый пароль (последние 2 можно объединить на одном экране, в случае неправильного кода выводить алерт и обнулять поля)

Примеры: 

<img width="245" alt="Снимок экрана 2022-07-20 в 14 17 54" src="https://user-images.githubusercontent.com/86912772/179970316-e5481689-1e10-4147-95a2-f07314b397ce.png">

<img width="245" alt="Снимок экрана 2022-07-20 в 14 18 03" src="https://user-images.githubusercontent.com/86912772/179970353-ec112bdb-2754-479e-9dab-ec2c3af0925f.png">

<img width="245" alt="Снимок экрана 2022-07-20 в 14 18 11" src="https://user-images.githubusercontent.com/86912772/179970480-f64af966-298a-42d3-b76d-c0bbb0feab68.png">

**Comment by kozhemin** [comment]
Скорее всего этот экран не потребуется. Так как аутентификация по номеру телефона не подразумевает ввода пароля
