### ISSUE TITLE
Экран (вкладка таббара) со списком гостей (прототип)

### ISSUE THREAD

**Issue by 1ce-scream** [1ce-scream/GB_PartyScheduler#9]
Каждый участник может подтвердить свое присутствие на событии (в идеале это может быть segment control для указания своего статуса, если пользователь не организатор события). Посмотреть статус подтверждения других участников и наличие +1 или детей. 

Пример:

![179840208-cdd6336e-7cdd-4e5b-8c1a-f782a209ea62](https://user-images.githubusercontent.com/86912772/180176260-78b6fad4-b7e9-4515-8db7-8a74892a8a37.png)

По жесту pull to refresh (swipe down) показывается view с поиском, фильтрами и количеством гостей

Пример: 

![IMG_4209](https://user-images.githubusercontent.com/86912772/180176676-2e149e52-f7ab-495c-b9d7-ee28d74f1abe.jpg)

**Comment by kozhemin** [comment]
> А вот дизайн я бы немного доработал. Убрал бы паддинги, чтоб расстояние между ячейками было меньше. И сами ячейки модифицировал бы. Вместо простой галочки 3 разноцветных варианта: 􀁢, 􀁎, 􀁜 (да, нет, возможно) и наличие + 1 (С изменением модели User, естественно). А в навигейшнБар кнопку добавить/пригласить гостя и Edit(). На лист повесил бы onDelete, onMove и поиск. И фон, конечно, на стандартный .darkColor поменял бы.

**Comment by kozhemin** [comment]
https://github.com/1ce-scream/GB_PartyScheduler/pull/31

**Comment by 1ce-scream** [comment]
Отлично
